webtalk_init -webtalk_dir /media/sytrics/Storage/git/EVEEX-FPGA/fpga4students-image-processing/project_test/project_test.sim/sim_1/behav/xsim/xsim.dir/tb_simulation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 17 16:46:21 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "422ce672-e639-40f8-94ee-a3c326ddf1d3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7e02fe4af787411b98e48df2ae559845" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Pop" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Pop!_OS 20.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1911.533 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "21.24_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "156304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2263983385 -regid "" -xml /media/sytrics/Storage/git/EVEEX-FPGA/fpga4students-image-processing/project_test/project_test.sim/sim_1/behav/xsim/xsim.dir/tb_simulation_behav/webtalk/usage_statistics_ext_xsim.xml -html /media/sytrics/Storage/git/EVEEX-FPGA/fpga4students-image-processing/project_test/project_test.sim/sim_1/behav/xsim/xsim.dir/tb_simulation_behav/webtalk/usage_statistics_ext_xsim.html -wdm /media/sytrics/Storage/git/EVEEX-FPGA/fpga4students-image-processing/project_test/project_test.sim/sim_1/behav/xsim/xsim.dir/tb_simulation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
